name: NodeJS CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions: read-all

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See https://nodejs.org/en/about/releases/
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use NodeJS ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install souffle
              run: |
                  sudo wget https://souffle-lang.github.io/ppa/souffle-key.public -O /usr/share/keyrings/souffle-archive-keyring.gpg
                  echo "deb [signed-by=/usr/share/keyrings/souffle-archive-keyring.gpg] https://souffle-lang.github.io/ppa/ubuntu/ stable main" | sudo tee /etc/apt/sources.list.d/souffle.list
                  sudo apt update
                  sudo apt install souffle

            - name: Install and lint
              run: |
                  npm install
                  npm link
                  npm run lint
                  soufle-ts --version

            - name: Test and generate coverage report
              run: npm test

            # - name: Upload coverage to CodeCov
            #   uses: codecov/codecov-action@v3
            #   with:
            #       name: codecov-umbrella
            #       directory: ./coverage/
            #       fail_ci_if_error: true
            #       verbose: true
